---
- name: Start or Stop Azure VM
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Stop virtual machine
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}"
        started: no
      when: power == "off"

    - name: Start virtual machine
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}"
        started: yes
      when: power == "on"
