---
- name: Start Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Stop virtual machine
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}"
        started: no
